#!/usr/bin/env node
/**
 * Write `web/src/styles/_tokens.scss` from the stock theme.
 *
 *   node web/scripts/build-tokens.mjs            # write the sheet
 *   node web/scripts/build-tokens.mjs --stdout   # print it instead
 *
 * The generated file stays committed, so nothing has to run before `vite
 * build`. `scripts/ratchets/tokens.mjs` regenerates to memory on every check
 * and fails when the committed file has drifted, which is what makes hand
 * editing the sheet a CI failure rather than a surprise three commits later.
 *
 * It also writes `vela/assets/theme-tokens.json`: the whitelist, the aliases
 * and the value rules, so `vela/themes.py` validates an imported theme against
 * this module's list rather than a second copy of it that can drift from it.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import theme from '../src/design/theme.vela.json' with { type: 'json' };
import {
  ALIASES,
  CANONICAL,
  CANONICAL_TOKENS,
  CHANNEL_TOKENS,
  FONT_ALLOW_LIST,
  GROUP_TYPES,
  RAMPED_ROLES,
  RAMP_STEPS,
  RAMP_STOPS,
  SCALES,
  SCHEMA_VERSION,
  SWATCH_TOKENS,
  derive,
} from '../src/design/tokens.js';

const root = fileURLToPath(new URL('../..', import.meta.url));
export const SHEET_PATH = path.join(root, 'web/src/styles/_tokens.scss');
export const WHITELIST_PATH = path.join(root, 'vela/assets/theme-tokens.json');

const GROUP_NOTES = {
  ground:
    'Semantic surfaces, outermost first: the ground the rail sits on, the\n     rail itself, the workspace beside it, an optional context panel, then\n     cards, inset fields and overlays.',
  role: 'One base colour per role. The 100-900 steps below are derived from\n     these on the shared lightness scale; a theme never sets a step.',
  shadow:
    'Elevation. On a light ground, an edge and a soft ink shadow; on a dark\n     one, an edge and ambient darkness.',
};

const RAMP_NOTE =
  'Tonal ramps, derived in OKLCH from the role above on the shared\n     lightness scale, so step 600 of one role weighs what step 600 of\n     another does.';

function block(tokens, base) {
  const derived = derive(tokens, base);
  const lines = [];
  const write = (name) => lines.push(`  ${name}: ${derived[name]};`);

  for (const [group, names] of Object.entries(CANONICAL)) {
    if (GROUP_NOTES[group]) lines.push(`\n  /* ${GROUP_NOTES[group]} */`);
    else lines.push('');
    names.forEach(write);
  }

  lines.push(`\n  /* ${RAMP_NOTE} */`);
  for (const role of RAMPED_ROLES) {
    RAMP_STEPS.forEach((step) => write(`--${role}-${step}`));
    lines.push('');
  }
  lines.pop();

  lines.push(
    '\n  /* Tints and the accent values that carry text. `--accent-strong` is the\n' +
      '     first ramp step that clears 4.5:1 on the accent tint, walked from the\n' +
      '     base, rather than a step chosen by eye: the raw violet clears that on\n' +
      '     white and not on a tinted pill. */',
  );
  for (const name of [
    '--accent-soft',
    '--accent-strong',
    '--accent-line',
    '--green-soft',
    '--amber-soft',
    '--red-soft',
    '--nav-active-text',
    '--nav-active-bg',
    '--nav-active-bar',
  ]) {
    write(name);
  }

  lines.push(
    '\n  /* The same three colours as bare channels, for `rgba(var(--scrim-rgb), 0.5)`.\n' +
      '     A veil over a photograph has to composite and interpolate exactly as it\n' +
      '     always did; `color-mix()` reaches the colour but not the gradient. */',
  );
  CHANNEL_TOKENS.forEach((name) => write(`${name}-rgb`));
  write('--veil');
  write('--veil-plain');

  lines.push('\n  /* Legacy names the stylesheet still reads, kept as aliases. */');
  Object.keys(ALIASES).forEach(write);

  return lines;
}

function scales() {
  const lines = [];
  for (const [name, note] of [
    ['space', 'Rhythm. Padding, gap and margin read these; widths and heights do not.'],
    ['type', 'The type scale. Headings sit at weight 500 and never past it.'],
    ['motion', 'Motion, zeroed under `prefers-reduced-motion` in `_base.scss`.'],
    ['layout', 'Fixed dimensions. Not rhythm, and not a theme’s business.'],
  ]) {
    lines.push(`\n  /* ${note} */`);
    for (const [token, value] of Object.entries(SCALES[name])) lines.push(`  ${token}: ${value};`);
  }
  return lines;
}

export function sheet() {
  return `/* Generated by web/scripts/build-tokens.mjs from web/src/design/theme.vela.json.
   Do not edit by hand: the token ratchet regenerates this file on every check
   and fails when the committed copy has drifted. Change the theme, or change
   the recipe in web/src/design/tokens.js, and run the generator.

   Colour comes from the Vela brand kit: Deep Navy #111A27, Vela Violet #7B4DFF,
   Soft Lavender #C9B0FF, Bright Cyan #2FD3F6, Cloud White #F6F8FB and Slate
   Gray #70798A. Anything used as text carries at least 4.5:1 against the
   surface behind it. \`--cyan\` marks running things; it is drawn as a dot or a
   line rather than as text, so it is tuned per base to stay visible rather
   than to read.

   The dark tokens stay scoped under [data-theme='dark'] because an app window
   may ask for a dark title bar under a light base, and that override is what
   scopes it. */

@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

:root,
[data-theme='light'] {${block(theme.tokens.light, 'light').join('\n')}
${scales().join('\n')}

  color-scheme: light;
}

[data-theme='dark'] {${block(theme.tokens.dark, 'dark').join('\n')}

  color-scheme: dark;
}
`;
}

/** What the server validates an imported theme against. One list, not two. */
export function whitelist() {
  return {
    schema_version: SCHEMA_VERSION,
    generated_by: 'web/scripts/build-tokens.mjs',
    tokens: Object.fromEntries(
      CANONICAL_TOKENS.map((name) => [
        name,
        GROUP_TYPES[Object.entries(CANONICAL).find(([, names]) => names.includes(name))[0]],
      ]),
    ),
    groups: CANONICAL,
    aliases: ALIASES,
    fonts: FONT_ALLOW_LIST,
    swatches: SWATCH_TOKENS,
    ramp: { roles: RAMPED_ROLES, steps: RAMP_STEPS, stops: RAMP_STOPS },
  };
}

if (
  import.meta.url === `file://${process.argv[1]}` ||
  process.argv[1]?.endsWith('build-tokens.mjs')
) {
  if (process.argv.includes('--stdout')) {
    process.stdout.write(sheet());
  } else {
    writeFileSync(SHEET_PATH, sheet());
    mkdirSync(path.dirname(WHITELIST_PATH), { recursive: true });
    writeFileSync(WHITELIST_PATH, `${JSON.stringify(whitelist(), null, 2)}\n`);
    console.log(`build-tokens: wrote _tokens.scss and theme-tokens.json.`);
  }
}
