"""Smoke-test the actual portable server from a fresh directory and data home."""
import json
import os
import re
import shutil
import socket
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import HTTPRedirectHandler, Request, build_opener, ProxyHandler

ROOT = Path(__file__).resolve().parent.parent


def check_portable_swap():
    """Run the real swap script, on this OS, against a disposable folder.

    The script Vela writes to replace itself is the one step the engine cannot
    supervise: by the time it runs, the process that wrote it is gone. So it is
    exercised here for real — generated by the same function the updater uses,
    run by the same shell — against two throwaway directories that are not a
    Vela install. The relaunch command is replaced with a harmless one so the
    check does not start a server.
    """
    import sys as _sys

    _sys.path.insert(0, str(ROOT))
    from vela.updates import posix_swap_script, windows_swap_script

    with tempfile.TemporaryDirectory(prefix='vela-swap-') as temporary:
        work = Path(temporary)
        install = work / 'Vela'
        staged = work / 'Vela.new'
        previous = work / 'Vela.previous'
        install.mkdir()
        staged.mkdir()
        (install / 'marker.txt').write_text('old', encoding='utf-8')
        (staged / 'marker.txt').write_text('new', encoding='utf-8')

        # A pid that has already exited, so the script's wait loop falls
        # straight through instead of waiting for a server that is not there.
        finished = subprocess.Popen([_sys.executable, '-c', 'pass'])
        finished.wait(timeout=30)
        gone = finished.pid

        if os.name == 'nt':
            script = work / 'apply.cmd'
            script.write_text(windows_swap_script(
                pid=gone, install_dir=install, staged=staged, previous=previous,
                relaunch='cmd /c exit'), encoding='utf-8')
            command = ['cmd.exe', '/c', str(script)]
        else:
            script = work / 'apply.sh'
            script.write_text(posix_swap_script(
                pid=gone, install_dir=install, staged=staged, previous=previous,
                relaunch='true'), encoding='utf-8')
            script.chmod(0o755)
            command = ['/bin/sh', str(script)]

        result = subprocess.run(command, cwd=work, capture_output=True, text=True, timeout=60)
        assert result.returncode == 0, f'Swap script failed: {result.stdout}{result.stderr}'
        assert (install / 'marker.txt').read_text(encoding='utf-8') == 'new', \
            'The swap did not put the new version in place'
        assert (previous / 'marker.txt').read_text(encoding='utf-8') == 'old', \
            'The swap did not keep the previous version to roll back to'
        assert not staged.exists(), 'The staging folder should have been moved, not copied'
    print('PASS: the portable swap replaces the install directory and keeps the previous one')


def serve_release(directory):
    """A local stand-in for the GitHub releases API, over loopback only.

    The update path must never be exercised against real releases: a check that
    downloads from GitHub is a check that can install a real new Vela on the
    machine running it. This serves a release document and its asset files from
    a directory, and `VELA_UPDATE_API` points the engine here.
    """
    import http.server
    import threading

    class Handler(http.server.SimpleHTTPRequestHandler):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, directory=str(directory), **kwargs)

        def log_message(self, *args):
            pass

    server = http.server.ThreadingHTTPServer(('127.0.0.1', 0), Handler)
    threading.Thread(target=server.serve_forever, daemon=True).start()
    return server


#: Run inside the engine against the local asset server. It prepares an update
#: — download, verify, back up — and stops there: `apply` is never called, so
#: nothing on the machine running this is replaced.
_PREPARE = '''
import json
from vela.config import load_config
from vela.settings import SettingsStore
from vela.backups import BackupStore
from vela.updates import UpdateChecker, UpdateError, UpdateJob

config = load_config()
settings = SettingsStore(config.settings_file)
checker = UpdateChecker(config, "0.0.1", settings=settings)
checker.check(force=True)
backups = BackupStore(config)
job = UpdateJob(config, checker, backups=backups)
before = len(backups.list())
try:
    prepared = job.prepare()
except UpdateError as exc:
    print(json.dumps({"refused": str(exc), "backed_up": len(backups.list()) > before}))
else:
    path, text = job.script_for("installer", prepared)
    print(json.dumps({
        "refused": None,
        "downloaded": prepared["asset"].is_file(),
        "backed_up": len(backups.list()) > before,
        "script": text,
    }))
'''


def check_update_over_http():
    """Download, verify and back up an update from a local asset server.

    This is the whole update path up to the handover, over real HTTP, with a
    real checksum sidecar — and then the same path again with the sidecar
    changed, to prove a download that does not match is refused *before*
    anything is backed up or replaced.
    """
    import hashlib
    import sys as _sys

    _sys.path.insert(0, str(ROOT))
    from vela.updates import platform_architecture

    with tempfile.TemporaryDirectory(prefix='vela-update-http-') as temporary:
        work = Path(temporary)
        releases = work / 'assets'
        releases.mkdir()
        # The installer path is forced below, so the fixture is named the way
        # the updater looks for it on *this* machine: an arm64 runner does not
        # download an x64 asset.
        asset_name = f'vela-server-9.9.9-windows-{platform_architecture()}-setup.exe'
        payload = b'a stand-in for a Vela release' * 500
        (releases / asset_name).write_bytes(payload)
        digest = hashlib.sha256(payload).hexdigest()
        sidecar = releases / (asset_name + '.sha256')
        sidecar.write_text(f'{digest}  {asset_name}\n', encoding='utf-8')

        server = serve_release(releases)
        try:
            base = f'http://127.0.0.1:{server.server_address[1]}'
            (releases / 'latest.json').write_text(json.dumps({
                'tag_name': 'v9.9.9',
                'body': 'Local fixture release.',
                'assets': [
                    {'name': asset_name, 'browser_download_url': f'{base}/{asset_name}',
                     'size': len(payload)},
                    {'name': asset_name + '.sha256',
                     'browser_download_url': f'{base}/{asset_name}.sha256'},
                ],
            }), encoding='utf-8')

            def run(data_dir):
                environment = {
                    **os.environ,
                    'VELA_DATA_DIR': str(data_dir),
                    'VELA_UPDATE_API': f'{base}/latest.json',
                    'VELA_UPDATE_CAPABILITY': 'installer',
                }
                done = subprocess.run([sys.executable, '-c', _PREPARE], cwd=ROOT,
                                      env=environment, capture_output=True, text=True,
                                      timeout=300)
                assert done.returncode == 0, done.stdout + done.stderr
                return json.loads(done.stdout.strip().splitlines()[-1])

            good = run(work / 'data-good')
            assert good['refused'] is None, good
            assert good['downloaded'] and good['backed_up'], good
            for flag in ('/VERYSILENT', '/SUPPRESSMSGBOXES', '/NORESTART', '/CLOSEAPPLICATIONS'):
                assert flag in good['script'], f'{flag} missing from the apply script'
            assert asset_name in good['script'], 'the apply script does not run the download'

            # The same release, with a sidecar that no longer matches the file.
            sidecar.write_text(f'{"0" * 64}  {asset_name}\n', encoding='utf-8')
            bad = run(work / 'data-bad')
            assert bad['refused'], 'a download that did not match its checksum was accepted'
            assert not bad['backed_up'], \
                'the update backed up before checking the download, which is the wrong order'
        finally:
            server.shutdown()
    print('PASS: an update downloads over HTTP, verifies its sidecar, backs up, and writes the '
          'installer apply script; a mismatched checksum is refused before anything is backed up')


def check_automations(request, hub):
    """Run a real workflow on the runtime that shipped inside this download.

    The point is that nothing else is installed on this machine: no sibling
    checkout, no Node on PATH. If the runtime was not bundled, say so plainly
    instead of passing quietly.
    """
    status = json.loads(request('/api/automations/status', headers=hub))
    if not status['available']:
        raise AssertionError('Packaged server cannot run automations: ' + str(status['detail']))
    assert 'node-runtime' in Path(status['node']).as_posix(), (
        f"Packaged server used {status['node']} instead of its bundled runtime")
    created = json.loads(request('/api/automations', 'POST', {'name': 'Bundle check'}, hub))
    document = {
        'version': 1,
        'meta': {},
        'nodes': [
            {'id': 'start', 'type': 'manual-trigger', 'config': {'payload': '{"name": "Vela"}'}},
            {'id': 'say', 'type': 'template', 'config': {'template': 'Hello {{name}}'}},
            {'id': 'note', 'type': 'log', 'config': {'level': 'info', 'prefix': 'bundle'}},
        ],
        'edges': [{'id': 'e1', 'source': 'start', 'target': 'say'},
                  {'id': 'e2', 'source': 'say', 'target': 'note'}],
    }
    saved = json.loads(request('/api/automations/' + created['id'], 'PUT',
                               {'revision': created['documentRevision'], 'document': document}, hub))
    assert saved['draftProblems'] == [], saved['draftProblems']
    run = json.loads(request('/api/automations/' + created['id'] + '/runs', 'POST', {}, hub))
    for _ in range(300):
        detail = json.loads(request('/api/automations/runs/' + run['id'], headers=hub))
        if detail['status'] not in ('queued', 'running'):
            break
        time.sleep(0.2)
    else:
        raise AssertionError('Automation run did not finish inside the packaged server')
    assert detail['status'] == 'succeeded', f"Automation run {detail['status']}: {detail['error']}"
    logged = [event for event in detail['events']
              if event['type'] == 'node-log' and event['nodeId'] == 'note']
    assert logged and logged[0]['data'] == 'Hello Vela', logged
    worker = detail['runtime']['worker']
    print(f"       automations ran on bundled Node {worker['node']} with tramo {worker['tramo']}")


def check_agent_desktops(request, hub):
    """What the download says about agent desktops, and whether it is true.

    Deliberately not "start one and run a task". The browser build is not inside
    the download — it lives in a per-user cache the runtime manages — so on a
    clean machine the honest result is *unavailable, with the sentence that says
    what to install*, and that sentence is the thing worth checking. Where the
    browser does happen to be present, this goes further and converts a desktop
    for real.

    What is always checked: the worker shipped, its provenance came with it, the
    integrity digest matches, and nothing here reached outside the bundle.
    """
    status = json.loads(request('/api/desktops/runtime', headers=hub))
    record = status.get('provenance') or {}
    assert record, 'Packaged server carries no agent runtime provenance'
    assert (record.get('installed') or {}).get('playwright-core'), (
        'Packaged server does not say which browser engine it was built against')
    assert (record.get('sources') or {}).get('digest'), (
        'Packaged server carries no integrity digest for its worker sources')

    if not status['available']:
        # The one failure mode that must never be silent: a reason that does not
        # say what to do about it.
        detail = status.get('detail') or ''
        assert detail and ('setup-browser-worker' in detail or 'Reinstall' in detail), (
            f'Packaged server says agent desktops are unavailable without saying why: {detail!r}')
        # A digest mismatch means the download is inconsistent, not that a
        # browser is missing, and that is a packaging failure rather than a
        # clean-machine expectation.
        assert 'does not match the rest of this Vela' not in detail, (
            'Packaged worker sources do not match the digest recorded at build time')
        print('PASS: agent desktops are packaged and report, with the browser build absent, '
              'exactly what to install — ' + detail)
        return

    node = Path(status['node']).as_posix()
    assert 'node-runtime' in node or 'node' in node.lower(), (
        f'Packaged server used {status["node"]} for the agent runtime')
    desktop = json.loads(request('/api/desktops', headers=hub))['defaultId']
    policy = json.loads(request(f'/api/desktops/{desktop}/policy', headers=hub))
    request(f'/api/desktops/{desktop}/policy', 'PUT',
            {'revision': policy['revision'], 'apps': ['chat-fixture']}, hub)
    started = json.loads(request(f'/api/desktops/{desktop}/enable-agent', 'POST', {}, hub))
    assert started['desktop']['kind'] == 'agent', started
    running = json.loads(request('/api/desktops/runtime', headers=hub))
    assert desktop in running['desktops'], running
    request(f'/api/desktops/{desktop}/disable-agent', 'POST', {}, hub)
    print('PASS: the packaged server started a managed browser for a desktop and gave it back')


def check_managed_web_apps(request, hub, work, base):
    """A managed web app installs, runs and answers on its own hostname.

    This is the part of hosting that a packaged download can get wrong on its
    own: the v3 schema is a data file, so a bundle that failed to collect
    `vela/assets` starts perfectly and then refuses every managed package. So
    the check builds a real package for this machine, installs it through the
    packaged server, starts the child process, and asks for it back through the
    app's own address -- which also proves the gateway is mounted in the bundle.

    The fixture's launcher runs the interpreter that built it. In a bundle smoke
    test that is the repository's Python, which is the right thing to prove
    here: what is under test is the packaged *server*, not the packaged Python.
    """
    import sys as _sys

    _sys.path.insert(0, str(ROOT / 'tests/fixtures/managed-web'))
    import fixture_build

    package = fixture_build.build_package(work / 'managed-package')
    review = json.loads(request('/api/managed/review', 'POST', {'folder': str(package)},
                                hub, timeout=120))
    assert review['trust']['execution'] == 'trusted-native', review
    assert review['integration'] == {'sdk': False, 'agent': False, 'storage': False}, review
    installed = json.loads(request(
        '/api/managed/review/' + review['review'] + '/install', 'POST',
        {'artifactDigest': review['artifactDigest'], 'packageDigest': review['packageDigest'],
         'trust': 'trusted-native'}, hub, timeout=60))
    assert installed['installed'], installed
    state = json.loads(request('/api/managed/' + review['id'] + '/start', 'POST',
                               headers=hub, timeout=60))
    assert state['state'] == 'ready', state

    ticket = json.loads(request('/api/managed/' + review['id'] + '/launch', 'POST', {}, hub))
    # Dialled by address with the app's name in the Host header, rather than by
    # resolving that name. A browser maps a `*.localhost` name to loopback
    # itself; Windows' own resolver does not, and this check is about the
    # packaged server routing by Host, not about whose resolver is asked.
    host = ticket['origin'].split('://', 1)[1]
    path = ticket['url'].split(ticket['origin'], 1)[1]
    entered = opener_request(base + path, headers={
        'Host': host, 'Sec-Fetch-Dest': 'document', 'Sec-Fetch-Mode': 'navigate'})
    cookie = next((value for name, value in entered.getheaders()
                   if name.lower() == 'set-cookie' and value.startswith('__Host-vela-app=')), None)
    assert entered.status == 303 and cookie, (entered.status, entered.getheaders())
    served = opener_request(base + '/healthz', headers={
        'Host': host, 'Cookie': cookie.split(';', 1)[0]})
    assert served.status == 200 and b'"ok"' in served.read(), served.status
    # And the same address gets nothing from Vela's own API, in the bundle too.
    refused = opener_request(base + '/api/apps', headers={
        'Host': host, 'Cookie': cookie.split(';', 1)[0], **hub})
    assert refused.status == 404, (refused.status, refused.read()[:200])

    request('/api/managed/' + review['id'] + '/stop', 'POST', headers=hub, timeout=30)
    removed = json.loads(request('/api/managed/' + review['id'], 'DELETE',
                                 {'eraseData': True}, hub, timeout=30))
    assert removed['dataErased'], removed


def opener_request(url, headers=None):
    """One request that does not follow redirects, for the launch exchange."""
    class NoRedirect(HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):
            return None

    opener = build_opener(ProxyHandler({}), NoRedirect)
    try:
        return opener.open(Request(url, headers=headers or {}), timeout=10)
    except HTTPError as error:
        return error


def main():
    check_portable_swap()
    check_update_over_http()
    # The automation runtime can still hold its executable for a moment after the
    # server stops, so a failed cleanup must not be read as a failed smoke test.
    with tempfile.TemporaryDirectory(prefix='vela-server-smoke-',
                                     ignore_cleanup_errors=True) as temporary:
        work = Path(temporary)
        shutil.copytree(ROOT / '.local/server-build/dist/Vela', work / 'Vela')
        executable = work / 'Vela' / ('Vela.exe' if os.name == 'nt' else 'Vela')
        shutil.copytree(ROOT / 'tests/fixtures/chat-fixture', work / 'chat-fixture')
        with socket.socket() as listener:
            listener.bind(('127.0.0.1', 0))
            port = listener.getsockname()[1]
        env = {k: v for k, v in os.environ.items()
               if not k.startswith(('VELA_', 'PYTHON', 'VIRTUAL_ENV'))}
        # Prove the download does not depend on a developer's Node installation.
        env['PATH'] = os.pathsep.join(
            entry for entry in env.get('PATH', '').split(os.pathsep)
            if entry and 'node' not in entry.lower())
        env['VELA_DATA_DIR'] = str(work / 'data')
        base = f'http://127.0.0.1:{port}'
        opener = build_opener(ProxyHandler({}))

        def request(path, method='GET', payload=None, headers=None, timeout=3):
            # Most calls answer immediately; stopping a managed service waits
            # out its graceful window first, so it says how long it may take
            # rather than reading a normal stop as a hung server.
            data = json.dumps(payload).encode() if payload is not None else None
            with opener.open(Request(base + path, data=data, method=method,
                                     headers={'Content-Type': 'application/json', **(headers or {})}), timeout=timeout) as response:
                return response.read()

        with (work / 'server.log').open('w', encoding='utf-8') as output:
            server = subprocess.Popen([str(executable), '--no-open-browser', '--no-tray', '--port', str(port)],
                                      cwd=work, env=env, stdout=output, stderr=subprocess.STDOUT,
                                      **({'creationflags': subprocess.CREATE_NO_WINDOW} if os.name == 'nt' else {}))
            try:
                for _ in range(200):
                    if server.poll() is not None:
                        raise AssertionError('Packaged server exited during startup')
                    try:
                        request('/api/health')
                        break
                    except (URLError, TimeoutError):
                        time.sleep(0.15)
                else:
                    raise AssertionError('Packaged server did not become ready')
                html = request('/').decode()
                assert '<!doctype html>' in html.lower(), 'Missing bundled dashboard'
                script = re.search(r'src="(/assets/[^\"]+\.js)"', html)
                assert script and len(request(script[1])) > 1000, 'Missing frontend JavaScript'
                token = json.loads(request('/api/session', headers={'X-Vela-Bootstrap': '1'}))['token']
                hub = {'Authorization': 'Bearer ' + token}
                review = json.loads(request('/api/releases/prepare', 'POST', {'folder': str(work / 'chat-fixture')}, hub))
                request('/api/releases/' + review['review'] + '/commit', 'POST',
                        {'capabilities': review['capabilities'], 'operations': review['operations']}, hub)
                assert b'Vela' in request('/apps/chat-fixture/_vela/sdk.js'), 'Missing bundled SDK'
                session = json.loads(request('/api/apps/chat-fixture/session', 'POST', headers=hub))
                app = {'Authorization': 'Bearer ' + session['token']}
                request('/api/app/storage', 'PUT', {'value': {'messages': []}, 'revision': 0}, app)
                assert json.loads(request('/api/app/storage', headers=app))['value'] == {'messages': []}
                check_automations(request, hub)
                check_agent_desktops(request, hub)
                check_managed_web_apps(request, hub, work, base)
                # psutil is imported lazily, so a bundle that failed to collect
                # it starts fine and only reports available: false here.
                metrics = json.loads(request('/api/system/metrics', headers=hub))
                assert metrics['available'], 'Packaged server has no psutil: the desk loses System and Volume'
                assert metrics['memory']['total'] > 0 and metrics['uptime']['seconds'] >= 0, metrics
                print('PASS: relocated server starts, serves dashboard/assets, validates and installs an app, '
                      'serves SDK, stores app data, reports system metrics, runs an automation on its '
                      'bundled runtime, carries a verified agent desktop runtime, and installs, runs '
                      'and publishes a managed web app on its own hostname')
            except Exception:
                output.flush()
                print((work / 'server.log').read_text(encoding='utf-8'))
                raise
            finally:
                server.terminate()
                try:
                    server.wait(timeout=10)
                except subprocess.TimeoutExpired:
                    server.kill()
                    server.wait()


if __name__ == '__main__':
    main()
