"""On-the-fly manifest.webmanifest + sw.js generation for web apps.

These are generated from app.json at request time; they are NOT files in the
app folder.
"""

import json
from pathlib import Path

from .manifest import Manifest

DEFAULT_THEME_COLOR = "#9184d9"
DEFAULT_BACKGROUND_COLOR = "#0f1420"


def build_web_manifest(manifest: Manifest) -> dict:
    web = manifest.web
    return {
        "name": manifest.name,
        "short_name": manifest.name,
        "description": manifest.description,
        "start_url": ".",
        "scope": ".",
        "display": "standalone",
        "theme_color": (web.theme_color if web else None) or DEFAULT_THEME_COLOR,
        "background_color": (web.background_color if web else None) or DEFAULT_BACKGROUND_COLOR,
        "icons": [
            {"src": "icon-192.png", "sizes": "192x192", "type": "image/png"},
            {"src": "icon-512.png", "sizes": "512x512", "type": "image/png"},
        ],
    }


def build_service_worker(manifest: Manifest, app_dir: Path) -> str:
    """Network-first service worker for an installed app.

    Navigations are network-first (a fresh deploy wins immediately) with the
    cached shell as an offline fallback only. Cache-first applies solely to
    same-origin static assets on an explicit extension allowlist; API calls
    and non-GET requests are never cached. The cache name is versioned and
    older caches for this same app are deleted on activate (caches belonging
    to the hub or other apps are never touched).
    """
    cache_name = f"vela-{manifest.id}-{manifest.version}"
    cache_prefix = f"vela-{manifest.id}-"
    precache = ["./"]
    return f"""// Generated by Vela for app "{manifest.id}" — do not edit.
const CACHE = {json.dumps(cache_name)};
const CACHE_PREFIX = {json.dumps(cache_prefix)};
const PRECACHE = {json.dumps(precache)};
const SCOPE_PATH = new URL(self.registration.scope).pathname;

// Static assets that may be served cache-first.
const CACHEABLE = /\\.(?:css|js|svg|png|jpe?g|webp|gif|ico|woff2?|ttf|otf|webmanifest|json)$/;

self.addEventListener("install", (event) => {{
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting())
  );
}});

self.addEventListener("activate", (event) => {{
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
}});

self.addEventListener("fetch", (event) => {{
  if (event.request.method !== "GET") return; // network only
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return; // never touch cross-origin
  const rel = url.pathname.startsWith(SCOPE_PATH) ? url.pathname.slice(SCOPE_PATH.length) : url.pathname;
  if (rel === "api" || rel.startsWith("api/") || rel.includes("/api/")) return; // sensitive: always network

  // Documents/navigations: network-first so an updated app is picked up
  // immediately; the cached shell is only an offline fallback.
  if (event.request.mode === "navigate" || (event.request.headers.get("accept") || "").includes("text/html")) {{
    event.respondWith(
      fetch(event.request)
        .then((response) => {{
          if (response.ok) {{
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put("./", copy));
          }}
          return response;
        }})
        .catch(() => caches.match("./"))
    );
    return;
  }}

  if (!CACHEABLE.test(url.pathname)) return; // not on the allowlist: network
  event.respondWith(
    caches.match(event.request).then((hit) => {{
      const fresh = fetch(event.request).then((response) => {{
        if (response.ok) {{
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(event.request, copy));
        }}
        return response;
      }});
      return hit || fresh;
    }})
  );
}});
"""
